# Generated by Django 3.0.8 on 2020-08-31 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('i_infra_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=500)),
                ('c_code', models.CharField(max_length=100)),
                ('c_address', models.CharField(max_length=1000)),
                ('c_description', models.CharField(max_length=1000)),
                ('c_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('i_parent_branch', models.IntegerField()),
                ('c_status', models.CharField(max_length=10)),
                ('d_created_at', models.DateTimeField(auto_now_add=True)),
                ('d_updated_at', models.DateTimeField(auto_now=True)),
                ('c_created_by', models.CharField(max_length=50)),
                ('c_updated_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('i_branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=500)),
                ('c_code', models.CharField(max_length=100)),
                ('c_address', models.CharField(max_length=1000)),
                ('c_description', models.CharField(max_length=1000)),
                ('c_logo', models.CharField(max_length=500)),
                ('c_status', models.CharField(max_length=10)),
                ('d_created_at', models.DateTimeField(auto_now_add=True)),
                ('d_updated_at', models.DateTimeField(auto_now=True)),
                ('c_created_by', models.CharField(max_length=50)),
                ('c_updated_by', models.CharField(max_length=50)),
                ('i_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='Backend.Infrastructure')),
                ('i_university', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='university', to='Backend.Infrastructure')),
            ],
        ),
        migrations.CreateModel(
            name='Academic_years',
            fields=[
                ('i_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_academic_year', models.CharField(max_length=50)),
                ('c_description', models.CharField(max_length=1000)),
                ('c_status', models.CharField(max_length=10)),
                ('d_created_at', models.DateTimeField(auto_now_add=True)),
                ('d_updated_at', models.DateTimeField(auto_now=True)),
                ('c_created_by', models.CharField(max_length=50)),
                ('c_updated_by', models.CharField(max_length=50)),
                ('i_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Branch')),
            ],
        ),
    ]
