# Generated by Django 3.0.8 on 2020-09-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('i_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_class_name', models.CharField(max_length=100)),
                ('c_description', models.CharField(max_length=1000)),
                ('c_room', models.CharField(max_length=25)),
                ('c_status', models.CharField(max_length=10)),
                ('d_created_at', models.DateTimeField(auto_now_add=True)),
                ('d_updated_at', models.DateTimeField(auto_now=True)),
                ('c_created_by', models.CharField(max_length=50)),
                ('c_updated_by', models.CharField(max_length=50)),
                ('i_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('i_section_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_section_name', models.CharField(max_length=100)),
                ('c_description', models.CharField(max_length=1000)),
                ('c_room', models.CharField(max_length=25)),
                ('c_status', models.CharField(max_length=10)),
                ('d_created_at', models.DateTimeField(auto_now_add=True)),
                ('d_updated_at', models.DateTimeField(auto_now=True)),
                ('c_created_by', models.CharField(max_length=50)),
                ('c_updated_by', models.CharField(max_length=50)),
                ('i_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Branch')),
                ('i_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('i_subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('i_subject_name', models.CharField(max_length=1000)),
                ('c_description', models.CharField(max_length=1000)),
                ('c_status', models.CharField(max_length=10)),
                ('d_created_at', models.DateTimeField(auto_now_add=True)),
                ('d_updated_at', models.DateTimeField(auto_now=True)),
                ('c_created_by', models.CharField(max_length=50)),
                ('c_updated_by', models.CharField(max_length=50)),
                ('i_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Branch')),
                ('i_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Class')),
                ('i_section_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.Section')),
            ],
        ),
    ]
