# Generated by Django 3.0.8 on 2020-09-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_class_section_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('i_syllabus_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_chapter_no', models.CharField(max_length=100)),
                ('c_chapter_name', models.CharField(max_length=200)),
                ('c_page_from', models.CharField(max_length=50)),
                ('c_page_to', models.CharField(max_length=50)),
                ('d_date_from', models.DateField()),
                ('d_date_to', models.DateField()),
                ('c_status', models.CharField(max_length=10)),
                ('d_created_at', models.DateTimeField(auto_now_add=True)),
                ('d_updated_at', models.DateTimeField(auto_now=True)),
                ('c_created_by', models.CharField(max_length=50)),
                ('c_updated_by', models.CharField(max_length=50)),
                ('i_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Branch')),
                ('i_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Class')),
                ('i_section', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='Backend.Section')),
                ('i_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_chapter',
            fields=[
                ('i_sub_chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_sub_chapter_no', models.CharField(max_length=100)),
                ('c_sub_chapter_name', models.CharField(max_length=200)),
                ('c_page_from', models.CharField(max_length=50)),
                ('c_page_to', models.CharField(max_length=50)),
                ('d_date_from', models.DateField()),
                ('d_date_to', models.DateField()),
                ('c_status', models.CharField(max_length=10)),
                ('d_created_at', models.DateTimeField(auto_now_add=True)),
                ('d_updated_at', models.DateTimeField(auto_now=True)),
                ('c_created_by', models.CharField(max_length=50)),
                ('c_updated_by', models.CharField(max_length=50)),
                ('i_syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby_club',
            fields=[
                ('i_hobby_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_hobby_name', models.CharField(max_length=100)),
                ('c_description', models.CharField(max_length=300)),
                ('c_status', models.CharField(max_length=10)),
                ('d_created_at', models.DateTimeField(auto_now_add=True)),
                ('d_updated_at', models.DateTimeField(auto_now=True)),
                ('c_created_by', models.CharField(max_length=50)),
                ('c_updated_by', models.CharField(max_length=50)),
                ('i_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby_assign_class',
            fields=[
                ('i_hobby_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_created_at', models.DateTimeField(auto_now_add=True)),
                ('d_updated_at', models.DateTimeField(auto_now=True)),
                ('c_created_by', models.CharField(max_length=50)),
                ('c_updated_by', models.CharField(max_length=50)),
                ('i_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Class')),
                ('i_hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Hobby_club')),
            ],
        ),
    ]
