# Generated by Django 3.0.8 on 2020-09-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_hobby_assign_class_hobby_club_sub_chapter_syllabus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infrastructure',
            old_name='i_parent_branch',
            new_name='i_university',
        ),
    ]
